name: Android CI

on: [ push ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./AndroidAPP

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        working-directory: ${{env.working-directory}}
        run: chmod +x gradlew
      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: gradlew test

  build:
    name: Build ExamApp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        working-directory: ${{env.working-directory}}
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ${{env.working-directory}}
        run: gradlew build
