name: Android CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AndroidAPP
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  
  instrumentation-test:
    name: Android Instrumentation Tests
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./AndroidAPP
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
          FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew.bat connectedAndroidTest
  
  unit-test:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AndroidAPP
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test
